# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- script: |
    docker build . -t orbitdb/orbit-db-tests --build-arg "SOURCE_BRANCH=$(Build.SourceBranchName)"
  displayName: 'Build OrbitDB test image'

- script: |
    docker run orbitdb/orbit-db-tests
  displayName: 'Build OrbitDB test image'